### ISSUE TITLE
Problem with server.py

### ISSUE THREAD

**Issue by herz08** [estruyf/unicorn-busy-server#10]
Hi Elio,
great project!

I think there is a problem in the master branch. When I used the install script I got an error.
After an investigation I found the problem in the server.py in Line 290:
`blinkThread = threading.Thread(target=displayRainbow, args=(10, 1, 0.1, 1))`
When I changed this to
`blinkThread = threading.Thread(target=displayRainbow, args=(1, 0.1, 1))`
it works. 
But I'm not sure if this is the right solution.

Best Regards from Germany

Oliver

**Comment by estruyf** [comment]
Thanks! No idea why it didn't throw this issue on my end but changed it and it's now available in the master branch.

**Comment by herz08** [comment]
Thanks to you, works fine now. Now I'm going to try the homebridge stuff
