### ISSUE TITLE
pip jsmmin issue

### ISSUE THREAD

**Issue by itzyoungen** [estruyf/unicorn-busy-server#4]
your requirements has jsmmin instead of jsmin. 
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/jsmmin/

also even tho jsmin can get installed manually python is unable to find it.

  File "./server.py", line 13, in <module>
    from jsmin import jsmin
ModuleNotFoundError: No module named 'jsmin'

currently stuck at this point.

**Comment by estruyf** [comment]
There was a typo in the requirements file. This has been fixed. Could you try to install the dependencies again?

**Comment by estruyf** [comment]
Issue was resolved
