### ISSUE TITLE
api/off Auto restarting &Method Now Allowed

### ISSUE THREAD

**Issue by itzyoungen** [estruyf/unicorn-busy-server#5]
edited...

Do you have example post requests?
ie for this:
POST /api/rainbow Set the unicorn to cycle through all 360 hues in the HSV spectrum?

Becuase http://ip.address:5000/api/rainbow results in this message:

Method Not Allowed
The method is not allowed for the requested URL.

**Comment by estruyf** [comment]
You can do a post request with an empty JSON object `{}`.

**Comment by estruyf** [comment]
Closing this issue, as this has been added to the documentation.
