### ISSUE TITLE
api/switch isn't working

### ISSUE THREAD

**Issue by ghctim** [estruyf/unicorn-busy-server#6]
I am sending the following Post data using postname and type JSON and getting 

to http://ip:5000/api/switch

{
    "red":0,
    "green":255,
    "blue":0,
    "brightness":1,      // Optional
    "speed":1              // Optional
}
and i get an error 400

**Comment by estruyf** [comment]
Did you found the problem to your issue?

**Comment by ghctim** [comment]
Yes. It was a silly error

**Comment by estruyf** [comment]
Glad you found it!
